name: create release
'on':
  push:
    branches:
      - main
jobs:
  release-project:
    name: release source files
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install gdown 
            
    - name: Create zip file for plain and pages
      run: |
        import gdown
        
        output="./temp.zip"
        
        def download_drive(url):
            gdown.download(url, output, quiet=False)

        if __name__=="__main__":
          download_drive('1RSsR-IPNI_FO_wT82pJO5sfaZSoEl38e')    
      shell: python
    - name: show files
      run: |
        ls -a
    - name: create github release
      id: create-new-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
      with:
        tag_name: new4${{ github.run_number }}
        release_name: new4${{ github.run_number }}
        draft: false
        prerelease: false
    - name: upload asset to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{steps.create-new-release.outputs.upload_url}}
        asset_path: ./temp.zip
        asset_name: tengyur.zip
        asset_content_type: text/zip
